name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create ZIP file
        run: zip -r LastLogin.zip LastLogin

      - name: Release to CurseForge
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        run: |
          curl -X POST "https://minecraft.curseforge.com/api/projects/your_project_id/upload-file" \
            -H "x-api-token: $CF_API_KEY" \
            -F "file=@LastLogin.zip" \
            -F "metadata={\"changelog\": \"Release notes\", \"changelogType\": \"text\", \"displayName\": \"v1.0.0\"}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: LastLogin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
